using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EntitiesEvents.Generator
{
    [Generator(LanguageNames.CSharp)]
    public sealed class RegisterAttributesGenerator : IIncrementalGenerator
    {
        private static readonly SymbolDisplayFormat FullyQualifiedTypeFormat =
            SymbolDisplayFormat.FullyQualifiedFormat;

        private static readonly DiagnosticDescriptor InvalidEventType = new DiagnosticDescriptor(
            id: "EEGEN001",
            title: "Invalid EntitiesEvents event type",
            messageFormat: "Type '{0}' cannot be registered as an EntitiesEvents event. Event types must be non-generic unmanaged structs that are accessible from generated code.",
            category: "EntitiesEvents.Generator",
            defaultSeverity: DiagnosticSeverity.Error,
            isEnabledByDefault: true);

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var registrations = context.CompilationProvider.Select(static (compilation, cancellationToken) =>
            {
                var builder = ImmutableArray.CreateBuilder<EventRegistration>();

                foreach (var attribute in compilation.Assembly.GetAttributes())
                {
                    cancellationToken.ThrowIfCancellationRequested();

                    if (!IsRegisterEventAttribute(attribute.AttributeClass))
                        continue;

                    var location = attribute.ApplicationSyntaxReference != null
                        ? attribute.ApplicationSyntaxReference.GetSyntax(cancellationToken).GetLocation()
                        : Location.None;

                    if (attribute.ConstructorArguments.Length != 1 ||
                        attribute.ConstructorArguments[0].Kind != TypedConstantKind.Type ||
                        !(attribute.ConstructorArguments[0].Value is INamedTypeSymbol eventType))
                    {
                        continue;
                    }

                    var eventTypeName = eventType.ToDisplayString(FullyQualifiedTypeFormat);
                    var displayName = eventType.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
                    var fingerprint = StableHash(eventTypeName).ToString("x8");
                    var generatedTypeName = SanitizeIdentifier(displayName) + "_" + fingerprint + "EventSystem";
                    var hintName = SanitizeIdentifier(eventTypeName) + "_" + fingerprint + ".entities-events.g.cs";

                    builder.Add(new EventRegistration(
                        eventTypeName,
                        displayName,
                        generatedTypeName,
                        hintName,
                        IsValidEventType(eventType),
                        location));
                }

                return builder.ToImmutable();
            });

            context.RegisterSourceOutput(registrations, static (sourceProductionContext, items) =>
            {
                var seen = new HashSet<string>(StringComparer.Ordinal);

                foreach (var item in items)
                {
                    sourceProductionContext.CancellationToken.ThrowIfCancellationRequested();

                    if (!seen.Add(item.EventTypeName))
                        continue;

                    if (!item.IsValid)
                    {
                        sourceProductionContext.ReportDiagnostic(Diagnostic.Create(
                            InvalidEventType,
                            item.Location,
                            item.DisplayName));
                        continue;
                    }

                    sourceProductionContext.AddSource(
                        item.HintName,
                        SourceText.From(GenerateSource(item), Encoding.UTF8));
                }
            });
        }

        private static string GenerateSource(EventRegistration item)
        {
            return
$@"// <auto-generated/>
#nullable enable

[assembly: global::Unity.Entities.RegisterGenericComponentType(typeof(global::EntitiesEvents.Internal.EventSingleton<{item.EventTypeName}>))]

namespace EntitiesEvents.Generated
{{
    [global::Unity.Burst.BurstCompile]
    [global::Unity.Entities.UpdateInGroup(typeof(global::EntitiesEvents.EventSystemGroup))]
    internal partial struct {item.GeneratedTypeName} : global::Unity.Entities.ISystem
    {{
        private global::Unity.Entities.EntityQuery _query;

        [global::Unity.Burst.BurstCompile]
        public void OnCreate(ref global::Unity.Entities.SystemState state)
        {{
            _query = state.GetEntityQuery(global::Unity.Entities.ComponentType.ReadWrite<global::EntitiesEvents.Internal.EventSingleton<{item.EventTypeName}>>());
            state.RequireForUpdate(_query);
        }}

        [global::Unity.Burst.BurstCompile]
        public void OnUpdate(ref global::Unity.Entities.SystemState state)
        {{
            state.Dependency.Complete();
            global::EntitiesEvents.Internal.EventSingletonRuntime.Update<{item.EventTypeName}>(_query);
        }}

        [global::Unity.Burst.BurstCompile]
        public void OnDestroy(ref global::Unity.Entities.SystemState state)
        {{
            if (_query.IsEmptyIgnoreFilter)
                return;

            var singleton = _query.GetSingleton<global::EntitiesEvents.Internal.EventSingleton<{item.EventTypeName}>>();
            global::EntitiesEvents.Internal.EventSingletonRuntime.Dispose<{item.EventTypeName}>(_query);
            state.EntityManager.DestroyEntity(_query.GetSingletonEntity());
        }}
    }}
}}
";
        }

        private static bool IsRegisterEventAttribute(INamedTypeSymbol? attributeClass)
        {
            if (attributeClass == null)
                return false;

            return attributeClass.ToDisplayString(FullyQualifiedTypeFormat) ==
                   "global::EntitiesEvents.RegisterEventAttribute";
        }

        private static bool IsValidEventType(INamedTypeSymbol eventType)
        {
            if (eventType.TypeKind != TypeKind.Struct)
                return false;

            if (eventType.IsGenericType || eventType.Arity != 0)
                return false;

            if (!eventType.IsUnmanagedType)
                return false;

            for (var type = eventType; type != null; type = type.ContainingType)
            {
                if (type.DeclaredAccessibility == Accessibility.Private ||
                    type.DeclaredAccessibility == Accessibility.Protected ||
                    type.DeclaredAccessibility == Accessibility.ProtectedAndInternal)
                {
                    return false;
                }
            }

            return true;
        }

        private static uint StableHash(string value)
        {
            unchecked
            {
                const uint offset = 2166136261;
                const uint prime = 16777619;

                var hash = offset;
                for (var i = 0; i < value.Length; i++)
                {
                    hash ^= value[i];
                    hash *= prime;
                }

                return hash;
            }
        }

        private static string SanitizeIdentifier(string value)
        {
            var builder = new StringBuilder(value.Length + 1);

            for (var i = 0; i < value.Length; i++)
            {
                var c = value[i];
                builder.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
            }

            if (builder.Length == 0 || !(char.IsLetter(builder[0]) || builder[0] == '_'))
                builder.Insert(0, '_');

            return builder.ToString();
        }

        private readonly struct EventRegistration
        {
            public EventRegistration(
                string eventTypeName,
                string displayName,
                string generatedTypeName,
                string hintName,
                bool isValid,
                Location location)
            {
                EventTypeName = eventTypeName;
                DisplayName = displayName;
                GeneratedTypeName = generatedTypeName;
                HintName = hintName;
                IsValid = isValid;
                Location = location;
            }

            public string EventTypeName { get; }
            public string DisplayName { get; }
            public string GeneratedTypeName { get; }
            public string HintName { get; }
            public bool IsValid { get; }
            public Location Location { get; }
        }
    }
}
